### ISSUE TITLE
[Bug] Timestamp is always created with ID 1

### ISSUE THREAD

**Issue by Mallets** [eclipse-zenoh/zenoh-backend-rocksdb#115]
### Describe the bug

Timestamp is always created with ID 1 when timestamp is empty.
I believe the ID of the local session should be used instead.

### To reproduce

See https://github.com/eclipse-zenoh/zenoh-backend-rocksdb/blob/f964ccd318ac09c6789f2c317403e12bc5af7a45/src/lib.rs#L471

### System info

NA

**Comment by Charles-Schleich** [comment]
Solved by https://github.com/eclipse-zenoh/zenoh-backend-rocksdb/pull/126
