### ISSUE TITLE
[Bug] Cross-builds failing on ARMs with RocksDB 0.19.0

### ISSUE THREAD

**Issue by JEnoch** [eclipse-zenoh/zenoh-backend-rocksdb#22]
### Describe the bug

Following bump of `rocksdb` from `0.18.0` to `0.19.0` all cross-builds for ARMs platforms are failing:
https://github.com/eclipse-zenoh/zenoh-backend-rocksdb/actions/runs/3656417087/jobs/6178992488

2 errors messages depending the target platform:

### `fatal error: string_view: No such file or directory`

RocksDB now requires **c++17** which is not supported by the GCC 5.4.0 used in the `ghcr.io/cross-rs/<arm target>:0.2.4` Docker image (base images of `jenoch/rust-cross:<arm targets>`).

**Solution**: upgrade all `jenoch/rust-cross` images to be based on recent `ghcr.io/cross-rs/<target>:edge` images which have been upgraded to GCC 9.4.0 (but with libc 2.31 vs. 2.23 before).
Still, after this change for 32-bit ARMs we face the 2nd error message:

### `error: '__uint128_t' was not declared in this scope`

RocksDB can now use 128 bit integers, which are not supported on 32-bit platforms.
This usage can be deactivated building RocksDB (C++) defining `HAVE_UINT128_EXTENSION=0`. But `rust-rocksdb 0.19.0` [forces this variable to `1`](https://github.com/rust-rocksdb/rust-rocksdb/blob/f5bf5ca7b51e7c77e4d12056dfcc901302c31bd5/librocksdb-sys/build.rs#L238)

### To reproduce

Run `release` workflow

### System info

- Zenoh commit: ff0fb2531

**Comment by JEnoch** [comment]
The `__uint128_t` issue has already been reported to `rust-rocksdb` team:
 - https://github.com/rust-rocksdb/rust-rocksdb/issues/681
Their is a PR, but not yet merged nor released:
 - https://github.com/rust-rocksdb/rust-rocksdb/issues/682

**Comment by JEnoch** [comment]
Waiting for the issue to be solved in a `rust-rocksdb` release, we rollback to version `0.18.0` (via #23)

**Comment by Mallets** [comment]
https://github.com/eclipse-zenoh/zenoh-backend-rocksdb/pull/27 updates `rust-rocksdb` to `0.20.1`, which can be cross-compiled to ARM (see https://github.com/eclipse-zenoh/zenoh-backend-rocksdb/actions/runs/4743527869).
